config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class ="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            You know
            <br />
            you want
            <br />
            to travel
          </div>
        <% end %>
      </div>
        
      <div class="col col-sm-4 hidden-xs-down slogan">
        Splurting out travel inspiration since 2019
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
        <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;&nbsp;
        <%= link_to 'About',about_path %>
      </div>
    </header>



    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModal">Contribute Your Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <%= f.input :saying, label: "What is the saying you want to add?" %>
              <br />
              <%= f.input :author, label: "Who is the author of the quote?" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <hr />
    <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Proudly created by <a href="https://alexandrialeary.netlify.com/">Alexandria</a><br />
            Want to build your own Splurty Web App - <a href="https://online.bootcampspot.com">Learn how to code here</a>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1>About Splurty</h1>

    <p>
    Splurty was built by <a target="_blank" href="http://github.com/MarcoMorawec">Alexandria</a>. A web developer on a mission to learn the technical skills needed to turn her ideas into reality.
  </p> 
  <p>
    If you want to learn how to code - start <a target="_blank" href="https://online.bootcampspot.com"> here</a>.
  </p>

    <div class="row">
    <div class="col-12 col-sm-4">
      <%= image_tag 'me.jpg', class: 'img-fluid' %>
    </div>

    <div class="col-12 col-sm-7 offset-sm-1">
      <h2 class="text-center">Alexandria Leary</h2>
      <br />
      <p>
        <a target="_blank" href="https://alexandrialeary.netlify.com/">Alexandria</a> is a web developer, world traveler and Business Support Manager for Bank of America. She plans to make it to all 7 continents before 2022. 
      </p>
      <p> She is currently learning as much as possible while finishing her MS in Information Systems from University of Colorado - Denver (December 2020). She is a Business Support Lead for the Global Information Security team and Bank of America.
      </p>
      <br />

    </div>
  </div>
  
  <br class="clear" />
    <br />
    <br />
    <br />
    <br />  
</div>

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.id %></span>
  Here's the <u>best unsolicited travel inspiration</u> you can find!
</h2> 
<br />
<br />

<h1><%= @quote.saying %></h1>
<h2 class="float-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>